import LegalPage from "@/components/LegalPage";

export const metadata = { title: "Terms of Service — PreConvara" };

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      subtitle="The rules and conditions for using PreConvara."
      lastUpdated="September 26, 2026"
      sections={[
        {
          heading: "1. Acceptance",
          body: <p>By creating an account or using PreConvara, you agree to these Terms. If you do not agree, do not use the service.</p>,
        },
        {
          heading: "2. The service",
          body: <p>PreConvara provides an AI-powered meeting preparation tool. You can create, save, and manage client briefs. We reserve the right to modify or discontinue features at any time with reasonable notice.</p>,
        },
        {
          heading: "3. Your account",
          body: <>
            <p>You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate information when registering. One person may not create multiple accounts to circumvent service limits.</p>
          </>,
        },
        {
          heading: "4. Acceptable use",
          body: <>
            <p>You must not use PreConvara to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Generate content that violates laws or third-party rights</li>
              <li>Attempt to reverse-engineer, scrape, or disrupt the service</li>
              <li>Impersonate other users or organisations</li>
              <li>Submit false, misleading, or harmful content</li>
            </ul>
          </>,
        },
        {
          heading: "5. Intellectual property",
          body: <p>The PreConvara application, design, and codebase are owned by us. The briefs you generate belong to you. You grant us a limited licence to process your input data solely to provide the service.</p>,
        },
        {
          heading: "6. AI-generated content",
          body: <p>Briefs generated by PreConvara are AI-produced and may contain inaccuracies. You are responsible for verifying information before using it in client meetings. We do not guarantee the accuracy or completeness of generated content.</p>,
        },
        {
          heading: "7. Limitation of liability",
          body: <p>PreConvara is provided "as is" without warranties of any kind. We are not liable for any loss of business, revenue, or data arising from your use of the service. Our total liability is limited to the amount you paid us in the past 12 months, or £50, whichever is greater.</p>,
        },
        {
          heading: "8. Termination",
          body: <p>We may terminate or suspend your account for violations of these Terms. You may delete your account at any time via the forgot-password page or by contacting support.</p>,
        },
        {
          heading: "9. Governing law",
          body: <p>These Terms are governed by the laws of England and Wales. Disputes will be subject to the exclusive jurisdiction of English courts.</p>,
        },
        {
          heading: "10. Changes",
          body: <p>We may update these Terms. We will notify you by email or an in-app notice at least 14 days before material changes take effect.</p>,
        },
      ]}
    />
  );
}
